### ISSUE TITLE
Requesting Attachment of Documents

### ISSUE THREAD

**Issue by ayesharajkapoor** [RafeekAyesha/Whatsapp_SudoCode#6]
Dear Rafeek,

It would be great if the app is capable of attaching the documents as well.
Kindy add this feature

**Comment by RafeekAyesha** [comment]
Dear Ayesha,

Thanks for suggesting this feature, we will add and let you know

**Comment by RafeekAyesha** [comment]
Dear Ayesha,

Thanks for your valuable suggestions, this feature is going to make our product great
